import { getOneShotHealth } from "@workify/evidence-engine";
import { Activity as ActivityIcon, Radio, RefreshCw } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function Activity() {
  const oneShot = await getOneShotHealth();
  const relayLabel = oneShot.status === "healthy" ? "Healthy" : oneShot.status === "low" ? "Low gas" : oneShot.status === "empty" ? "No gas" : "Unavailable";
  return <><div className="topline"><div><p className="kicker">Cross-chain observability</p><h1 className="page-title">Protocol activity</h1><p className="muted">Base, GenLayer, and authenticated 1Shot server-wallet status with finality-aware reporting.</p></div><span className={oneShot.status === "healthy" ? "status" : "status warning"}><Radio size={14} /> 1Shot {relayLabel}</span></div><div className="metrics"><div className="glass metric"><span className="muted">Base Sepolia</span><b>Ready</b><small>Escrow settlement layer</small></div><div className="glass metric"><span className="muted">GenLayer Bradbury</span><b>Ready</b><small>Consensus adjudication</small></div><div className="glass metric"><span className="muted">1Shot server wallet</span><b>{relayLabel}</b><small>{oneShot.walletAddress ? `${oneShot.walletAddress.slice(0, 8)}…${oneShot.walletAddress.slice(-6)}` : "Server-only configuration"}</small></div><div className="glass metric"><span className="muted">Base gas balance</span><b>{oneShot.balanceWei ? `${oneShot.balanceWei} wei` : "—"}</b><small>{oneShot.lastSuccessfulRelayAt ? `Last relay ${new Date(oneShot.lastSuccessfulRelayAt).toLocaleString()}` : "Manual refill monitoring"}</small></div></div><section className="section"><div className="topline"><div><p className="kicker">Event stream</p><h2 style={{ fontSize: 28 }}>Transaction history</h2></div><button className="button secondary" type="button"><RefreshCw size={15} /> Refresh</button></div><div className="glass"><table className="table"><thead><tr><th>Source</th><th>Event</th><th>Finality</th><th>Explorer</th></tr></thead><tbody><tr><td colSpan={4} className="empty-state"><ActivityIcon size={30} color="#2ee67b" /><p className="muted">Connect a wallet to load signed protocol activity.</p><span className="muted">No fabricated events or secrets are exposed.</span></td></tr></tbody></table></div></section></>;
}
