"use client";
import { useState } from "react";
import { encodeFunctionData, keccak256, parseUnits, stringToHex } from "viem";
import { BASE_SEPOLIA_USDC, MAX_JOB_TERM_SECONDS, MIN_JOB_TERM_SECONDS } from "@workify/protocol-types";
import { WalletButton } from "./WalletButton";

const erc20Abi=[{type:"function",name:"approve",stateMutability:"nonpayable",inputs:[{name:"spender",type:"address"},{name:"amount",type:"uint256"}],outputs:[{type:"bool"}]}] as const;
const escrowAbi=[{type:"function",name:"createFundedJob",stateMutability:"nonpayable",inputs:[{name:"jobId",type:"bytes32"},{name:"worker",type:"address"},{name:"reward",type:"uint128"},{name:"deliveryDeadline",type:"uint64"},{name:"specificationHash",type:"bytes32"},{name:"policyHash",type:"bytes32"}],outputs:[]}] as const;

export function NewJobForm(){const [account,setAccount]=useState<`0x${string}`>();const [status,setStatus]=useState("");const [workType,setWorkType]=useState("GITHUB_SOFTWARE");
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();try{if(!account||!window.ethereum)throw new Error("Connect a wallet first");const data=new FormData(event.currentTarget);const escrow=process.env.NEXT_PUBLIC_WORK_ESCROW_ADDRESS as `0x${string}`|undefined;if(!escrow)throw new Error("WorkEscrowV1 is not deployed yet");const worker=String(data.get("worker")) as `0x${string}`;const reward=parseUnits(String(data.get("reward")),6);const deadline=Math.floor(new Date(String(data.get("deadline"))).getTime()/1000);const now=Math.floor(Date.now()/1000);if(deadline<now+MIN_JOB_TERM_SECONDS||deadline>now+MAX_JOB_TERM_SECONDS)throw new Error("Deadline must be 15 minutes to 30 days away");const policy=String(data.get("policy"));const criteria=String(data.get("criteria")).split("\n").filter(Boolean).map((requirement,index)=>({id:`C-${String(index+1).padStart(3,"0")}`,requirement,severity:index===0?"CRITICAL":"HIGH",verificationMethod:"source-grounded",evidenceRequired:["public_url"],passCondition:requirement,failureCondition:`Evidence shows this requirement is not satisfied: ${requirement}`}));setStatus("Preparing canonical specification…");const prepared=await fetch("/api/jobs/prepare",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({version:"1.0.0",title:String(data.get("title")),description:String(data.get("description")),workType:String(data.get("workType")),deliverables:[String(data.get("title"))],criteria,authorizedSources:[],exclusions:[],policyVersion:policy})}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);return body as {jobId:`0x${string}`;specificationHash:`0x${string}`}});const policyHash=keccak256(stringToHex(policy));setStatus("Requesting USDC approval…");await window.ethereum.request({method:"eth_sendTransaction",params:[{from:account,to:BASE_SEPOLIA_USDC,data:encodeFunctionData({abi:erc20Abi,functionName:"approve",args:[escrow,reward]})}]});setStatus("Creating and funding job…");const tx=await window.ethereum.request({method:"eth_sendTransaction",params:[{from:account,to:escrow,data:encodeFunctionData({abi:escrowAbi,functionName:"createFundedJob",args:[prepared.jobId,worker,reward,BigInt(deadline),prepared.specificationHash,policyHash]})}]});setStatus(`Submitted: ${String(tx)}`)}catch(cause){setStatus(cause instanceof Error?cause.message:"Transaction failed")}}
 const policies:Record<string,string>={GITHUB_SOFTWARE:"github-software-v7.0",WEB_APPLICATION:"web-application-v7.0",RESEARCH_DATA:"research-data-v7.0",CONTENT_DOCUMENT:"content-document-v7.0",DESIGN_CREATIVE:"design-creative-v7.0"};
 return <form className="glass card form" style={{marginTop:28}} onSubmit={submit}><WalletButton onAccount={setAccount}/><div className="field"><label>Job title</label><input name="title" required placeholder="Fix session expiration handling"/></div><div className="field"><label>Description</label><textarea name="description" required rows={4} placeholder="Explain the requested outcome and constraints"/></div><div className="field"><label>Worker wallet</label><input name="worker" required pattern="0x[a-fA-F0-9]{40}" placeholder="0x…"/></div><div className="field"><label>Work type</label><select name="workType" value={workType} onChange={(event)=>setWorkType(event.target.value)}><option value="GITHUB_SOFTWARE">GitHub software</option><option value="WEB_APPLICATION">Web application</option><option value="RESEARCH_DATA">Research and data</option><option value="CONTENT_DOCUMENT">Content document</option><option value="DESIGN_CREATIVE">Design creative</option></select></div><input type="hidden" name="policy" value={policies[workType]}/><div className="field"><label>Acceptance criteria</label><textarea name="criteria" required rows={7} placeholder="One measurable requirement per line"/></div><div className="field"><label>Reward (Base Sepolia USDC)</label><input name="reward" required type="number" min="0.01" step="0.01" placeholder="250.00"/></div><div className="field"><label>Delivery deadline</label><input name="deadline" required type="datetime-local"/></div><button className="button" type="submit">Approve USDC and create job</button>{status&&<p className="muted">{status}</p>}</form>}
