import { BookOpen, CircleDollarSign, Code2, FileKey2, Gavel, GitBranch, LockKeyhole, Radar, RefreshCw, ServerCog, ShieldCheck, Workflow } from "lucide-react";
import { Nav } from "@/components/Nav";

const sections = ["Introduction", "Architecture", "Job Lifecycle", "Evidence System", "Verification Policies", "Retries", "Appeals", "Economics", "Settlement", "Automation Signer", "Security", "Contracts", "Operations"];

export default function Docs() {
  return <><Nav /><div className="docs"><aside><div className="docs-aside-title"><BookOpen size={17} /><span>Protocol manual</span></div>{sections.map((section) => <a href={`#${section.toLowerCase().replaceAll(" ", "-")}`} key={section}>{section}</a>)}</aside><article>
    <header className="docs-hero"><span className="page-icon"><BookOpen size={24} /></span><p className="kicker">Workify V4 · GenLayer V12 specification</p><h1>Protocol documentation</h1><p>Funded work, locked evidence, independent adjudication, appeals, and deterministic Base settlement.</p></header>
    <section className="doc-section" id="introduction"><span className="doc-icon"><ShieldCheck /></span><div><h2>Introduction</h2><p>Workify verifies whether a delivery satisfies predefined acceptance criteria. It does not ask an AI whether work is vaguely good. Base Sepolia holds USDC and GenLayer StudioNet V12 evaluates publicly reproducible evidence.</p></div></section>
    <section className="doc-section" id="architecture"><span className="doc-icon"><Workflow /></span><div><h2>Architecture</h2><pre>Client → Base V4 escrow → assigned worker → locked evidence → StudioNet V12 → appeal window → Base settlement</pre><p>Vercel provides the dApp, evidence APIs, receipt tracking, and bounded automation. MongoDB is an index only and never controls custody.</p></div></section>
    <section className="doc-section" id="job-lifecycle"><span className="doc-icon"><GitBranch /></span><div><h2>Job Lifecycle</h2><p><code>createFundedJob</code> transfers the exact USDC reward before a job is stored. The worker submits and locks evidence. The client starts a direct V12 review. A finalized verdict opens a five-minute appeal window before anyone can settle.</p></div></section>
    <section className="doc-section" id="evidence-system"><span className="doc-icon"><FileKey2 /></span><div><h2>Evidence System</h2><p>Evidence manifests contain canonical HTTPS URLs, MIME types, byte bounds, revisions, and hashes. Validators independently retrieve public sources. External content is untrusted data, never instructions.</p></div></section>
    <section className="doc-section" id="verification-policies"><span className="doc-icon"><Radar /></span><div><h2>Verification Policies</h2><p>V12 supports GitHub Software, Web Application, Research/Data, Content/Document, and Design/Creative policies. Each criterion returns PASS, PARTIAL, FAIL, or UNVERIFIABLE; critical failures are hard gates.</p></div></section>
    <section className="doc-section" id="retries"><span className="doc-icon"><RefreshCw /></span><div><h2>Retries</h2><p>Verification is zero-fee in the active StudioNet V12 direct-wallet flow. An UNDETERMINED outcome permits re-verification with the same locked evidence, up to three attempts. If the second attempt is also UNDETERMINED, it becomes the deterministic fallback.</p></div></section>
    <section className="doc-section" id="appeals"><span className="doc-icon"><Gavel /></span><div><h2>Appeals</h2><p>Either party may open one appeal during the 300-second Base window. Settlement freezes while the V12 appeal runs. The replacement result is recorded with <code>AppealResolved</code>.</p></div></section>
    <section className="doc-section" id="economics"><span className="doc-icon"><CircleDollarSign /></span><div><h2>Economics</h2><p>Verification and appeals cost zero GEN in the active direct flow. Base charges a 1% protocol fee only from the worker-awarded USDC share. Demo jobs are capped at 1 USDC.</p></div></section>
    <section className="doc-section" id="settlement"><span className="doc-icon"><LockKeyhole /></span><div><h2>Settlement</h2><p>PASS pays the worker share, PARTIAL pays adjudicated basis points, and FAIL or UNVERIFIABLE refunds the client. The terminal fallback splits gross escrow 50/50. Recipients are always derived from locked job state.</p></div></section>
    <section className="doc-section" id="automation-signer"><span className="doc-icon"><ServerCog /></span><div><h2>Automation Signer</h2><p>The Vercel Base signer is server-only, pays gas, and submits only allowlisted lifecycle calls. It cannot select recipients, alter payout amounts, or custody USDC. EIP-712 version <code>3</code> binds attestations to V4.</p></div></section>
    <section className="doc-section" id="security"><span className="doc-icon"><ShieldCheck /></span><div><h2>Security</h2><p>Controls include immutable hashes, strict source limits, prompt-injection boundaries, validator-side retrieval, replay nonces, fixed recipients, preflight simulation, receipt confirmation, SafeERC20, reentrancy guards, bounded retries, and permissionless expiry.</p></div></section>
    <section className="doc-section" id="contracts"><span className="doc-icon"><Code2 /></span><div><h2>Contracts and versioning</h2><p>Base V1–V3 and GenLayer V1–V11 remain as immutable historical source. WorkEscrowV4 and WorkVerifierV12 are the active releases. Versioning prevents deployed code from being overwritten and lets auditors reproduce every migration.</p></div></section>
    <section className="doc-section" id="operations"><span className="doc-icon"><ServerCog /></span><div><h2>Operations</h2><p>Automation is best effort and may be retried safely. Onchain deadlines and states remain authoritative. The explorer publishes only complete Base settlements joined to finalized V12 records; it never uses fixture data.</p></div></section>
  </article></div></>;
}
